CREATE TABLE `register_page` (
  `Name` varchar(50) NOT NULL,
  `Address` varchar(50) NOT NULL,
  `Batch` varchar(50) NOT NULL,
  `State` varchar(50) NOT NULL,
  `Course` varchar(100) NOT NULL,
  `Email` varchar(50) NOT NULL,
  `Phone` varchar(50) NOT NULL,
  `Fname` varchar(50) NOT NULL,
  `image` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
